In [3]:
"""
Learn Layers in tensorflow
"""
import tensorflow as tf
from tensorflow.keras.layers import MaxPool1D, Conv1D, GRU, Embedding
import numpy as np
x = tf.constant([1.,2.,3.,4.,5.])
x = tf.reshape(x,[1,5,1])
print(x)
max_pool_1d = MaxPool1D(pool_size=2,strides=1,padding='valid')
max_pool_1d(x)

tf.Tensor(
[[[1.]
  [2.]
  [3.]
  [4.]
  [5.]]], shape=(1, 5, 1), dtype=float32)


<tf.Tensor: shape=(1, 4, 1), dtype=float32, numpy=
array([[[2.],
        [3.],
        [4.],
        [5.]]], dtype=float32)>

In [4]:
input_shape = [1,3,1]
x = tf.random.normal(input_shape)
x = [[[1.],[1.],[1.]]]
x=  tf.constant(x)
print(np.shape(x))
y = Conv1D(2,2,activation='relu',input_shape=input_shape[1:])(x)
y

(1, 3, 1)


<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[0.5203111, 0.       ],
        [0.5203111, 0.       ]]], dtype=float32)>

In [5]:
input_shape= [20,30,100]
wm = tf.random.normal(input_shape)
layer1 = Conv1D(2,3,activation='relu',input_shape= input_shape[1:])(wm)
layer1

<tf.Tensor: shape=(20, 28, 2), dtype=float32, numpy=
array([[[0.07221573, 0.        ],
        [0.        , 0.        ],
        [0.        , 0.        ],
        ...,
        [1.0444515 , 0.677573  ],
        [0.        , 0.        ],
        [0.31786394, 0.        ]],

       [[0.92505425, 0.        ],
        [0.        , 0.        ],
        [0.        , 0.        ],
        ...,
        [0.        , 0.8224692 ],
        [0.        , 0.4760671 ],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.        ],
        [0.        , 0.80205685],
        ...,
        [2.6618416 , 1.1037397 ],
        [2.2515879 , 0.7100901 ],
        [0.        , 0.        ]],

       ...,

       [[0.        , 2.333603  ],
        [0.        , 0.        ],
        [0.44468293, 0.        ],
        ...,
        [3.2124019 , 1.9827898 ],
        [0.47302276, 0.        ],
        [0.63129115, 0.        ]],

       [[0.09896793, 0.        ],
        [0.63238716, 0. 

In [6]:
layer2 = MaxPool1D(pool_size=2,
   strides=2, padding='valid')(layer1)
layer2

<tf.Tensor: shape=(20, 14, 2), dtype=float32, numpy=
array([[[0.07221573, 0.        ],
        [2.2497315 , 0.09968897],
        [1.3521013 , 1.3498937 ],
        [1.5248837 , 0.        ],
        [0.        , 2.3611126 ],
        [1.5079203 , 0.92757344],
        [0.        , 1.8924961 ],
        [0.5380714 , 2.9613845 ],
        [1.527663  , 0.72158664],
        [0.8076539 , 0.9180021 ],
        [0.        , 0.        ],
        [1.2798171 , 2.1845696 ],
        [1.0444515 , 0.677573  ],
        [0.31786394, 0.        ]],

       [[0.92505425, 0.        ],
        [0.        , 0.        ],
        [0.42801973, 0.87234557],
        [1.0821056 , 2.7248878 ],
        [0.8064572 , 1.116822  ],
        [1.5215231 , 4.263307  ],
        [0.        , 0.        ],
        [0.20452277, 0.8588526 ],
        [0.5087959 , 0.        ],
        [1.2791827 , 1.1440439 ],
        [2.284571  , 0.0243528 ],
        [2.0381653 , 2.179853  ],
        [4.7406516 , 0.9527137 ],
        [0.        , 0.4760

In [7]:
layer3 = GRU(5,return_sequences=True)(layer2)
layer3
layer4 = GRU(5)(layer3)
layer4

<tf.Tensor: shape=(20, 5), dtype=float32, numpy=
array([[ 0.24228247,  0.2066411 , -0.346561  ,  0.25216344, -0.25318775],
       [ 0.30942157,  0.03706568, -0.24855015,  0.296805  , -0.22148298],
       [ 0.36702123,  0.14403388, -0.27047464,  0.43333378, -0.27834767],
       [ 0.256378  ,  0.25013855, -0.34810892,  0.2412619 , -0.26036426],
       [ 0.29574865,  0.36848655, -0.40376028,  0.3048951 , -0.35668948],
       [ 0.32203567,  0.14407247, -0.26786563,  0.38429213, -0.26706293],
       [ 0.34552905,  0.25909442, -0.32624727,  0.4354182 , -0.35005724],
       [ 0.24815495,  0.33151472, -0.40156114,  0.19766463, -0.28752983],
       [ 0.29333556,  0.21139765, -0.27862325,  0.35557047, -0.29623044],
       [ 0.28422427,  0.2461431 , -0.35102004,  0.30003792, -0.28339705],
       [ 0.16037321,  0.11877118, -0.23019788,  0.15820764, -0.15999357],
       [ 0.26066625,  0.23672943, -0.33013904,  0.30152202, -0.29168457],
       [ 0.2213781 ,  0.14238563, -0.24550918,  0.26800796, -0.

In [8]:
output =tf.keras.layers.Dense(5)(layer4)
output

<tf.Tensor: shape=(20, 5), dtype=float32, numpy=
array([[-0.49344966,  0.37857276, -0.25359154, -0.05404155,  0.30423626],
       [-0.39336586,  0.3098997 , -0.18572009, -0.02059776,  0.13358796],
       [-0.5090089 ,  0.4897538 , -0.29057682, -0.08847499,  0.25016272],
       [-0.5178701 ,  0.4004748 , -0.30143368, -0.0803498 ,  0.32746592],
       [-0.6442148 ,  0.5354788 , -0.4197948 , -0.1097627 ,  0.45044458],
       [-0.4772433 ,  0.44632566, -0.265297  , -0.07045108,  0.24749377],
       [-0.59290653,  0.56679976, -0.36703885, -0.09719539,  0.36930093],
       [-0.578409  ,  0.42192554, -0.35879958, -0.09578711,  0.39639997],
       [-0.49836546,  0.4656171 , -0.30761367, -0.07621065,  0.30304223],
       [-0.54372877,  0.44675156, -0.31241798, -0.08264682,  0.33825874],
       [-0.31706715,  0.23242436, -0.15348381, -0.02830741,  0.1850311 ],
       [-0.5172956 ,  0.43840152, -0.29680002, -0.06551619,  0.33358797],
       [-0.3884088 ,  0.33989057, -0.20065174, -0.05502929,  0.

In [22]:
x  = tf.random.normal([1,3])
x = tf.constant([[1,2,3],[4,5,6]])
y = Embedding(10,3,input_length=2)(x)
y

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[ 0.01472363,  0.0199596 ,  0.01687102],
        [-0.00859938,  0.00884118, -0.00175432],
        [ 0.04540434,  0.04544281, -0.04549066]],

       [[ 0.03512574, -0.00312926,  0.02134306],
        [ 0.02151671,  0.03727927,  0.00982778],
        [ 0.02994065, -0.01631261, -0.01636769]]], dtype=float32)>

In [12]:
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.layers import Input
wm = tf.random.normal([5,3,10])
wm  =tf.expand_dims(wm,3)
input_token = Input(shape=[3,10])
resnet_layer = ResNet50(include_top=False,weights=None)
# print(resnet_layer.summary())
y = resnet_layer(wm)

ValueError: Input 0 of layer conv1_conv is incompatible with the layer: expected axis -1 of input shape to have value 3 but received input with shape (5, 9, 16, 1)

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from gensim.models import word2vec  # 导入gensim包
from tensorflow.python.keras.models import Sequential
import re
from nltk.stem import WordNetLemmatizer

def clean_text(text):
    text = re.sub('[^a-zA-Z]', ' ', text)
    words = text.lower().split()
    lemmatizer = WordNetLemmatizer()
    lem_words = [lemmatizer.lemmatize(w, pos='n') for w in words]
    stopwords = {}.fromkeys([line.rstrip() for line in open('F:\\PycharmProjects\\NVDproject\\nvdcve\\stopwords.txt')])
    eng_stopwords = set(stopwords)
    words = [w for w in lem_words if w not in eng_stopwords]
    return words

years = ['2020','2021','2022']
infix = ''
infix = str(years[0])
for i in range(1,len(years)):
    infix += '-'+str(years[i])

# cwe_min_count = 500
cwe_min_count = 700
infix+='_'+str(cwe_min_count)

vec_len = 100
# vec_len = 200
# vec_len = 300
min_count = 1
window_len = 5
dense_unit = 128
wv_model_path  = '..//..//models//wv//'+infix+"_"+str(vec_len)+"_"+str(min_count)+"_"+str(window_len)+'.pkl'
label_path = '..\\..\\data\\clean\\nvdcve-1.1-'+infix+'_labels.csv'
n=30

cwe_count = 18  # 2020,2021,2022_700

def get_label_one_hot(list):
    values = np.array(list)
    n_values = np.max(values) + 1
    return np.eye(n_values)[values]

from tensorflow.keras.layers import Conv1D,Conv2D, BatchNormalization, Activation, MaxPool1D,MaxPool2D, Dropout, Flatten, Dense, GRU
from tensorflow.keras import Model

class TextCNN(Model):
    def __init__(self):
        super(TextCNN, self).__init__()
        self.c1 = Conv2D(filters=12, kernel_size=(3, vec_len), padding='same')  # 卷积层
        self.b1 = BatchNormalization()  # BN层
        self.a1 = Activation('relu')  # 激活层
        self.p1 = MaxPool2D(pool_size=(2, 2), strides=2, padding='same')  # 池化层
        self.d1 = Dropout(0.2)  # dropout层

        self.flatten = Flatten()
        self.f1 = Dense(dense_unit, activation='relu')
        self.d2 = Dropout(0.2)
        self.f2 = Dense(cwe_count, activation='softmax')

    def call(self, x):
        x = self.c1(x)
        x = self.b1(x)
        x = self.a1(x)
        x = self.p1(x)
        x = self.d1(x)

        x = self.flatten(x)
        x = self.f1(x)
        x = self.d2(x)
        y = self.f2(x)
        return y




if __name__ == '__main__':
    wv_model = word2vec.Word2Vec.load(wv_model_path)
    dataset = pd.read_csv(label_path, header=None)
    dataset.columns = ['cve_id', 'cwe_id', 'descript', 'label']
    dataset['contents'] = dataset['descript'].apply(clean_text)
    train_dataset = []
    for line in dataset['contents']:
        length = len(line)
        if length > n:
            line = line[:n]
            word2vec_matrix = (wv_model.wv[line])
            train_dataset.append(word2vec_matrix)
        else:
            word2vec_matrix = (wv_model.wv[line])
            pad_length = n - length
            pad_matrix = np.zeros([pad_length, vec_len]) + 1e-10
            word2vec_matrix = np.concatenate([word2vec_matrix, pad_matrix], axis=0)
            train_dataset.append(word2vec_matrix)
    # train_dataset = np.expand_dims(train_dataset, 3)
    label_dataset = get_label_one_hot(dataset['label'])

In [2]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(train_dataset, label_dataset, test_size=0.2, random_state=217)
batch_size = 32
train_data = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(batch_size)

In [3]:
train_data

<BatchDataset shapes: ((None, 30, 100), (None, 18)), types: (tf.float64, tf.float64)>

In [15]:
# for i in x_test:
#     print(i.shape)
for i in x_train:
    print(i.shape)
print("x_train_len",len(train_data))
# for i in y_test:
#     print(i.shape)

(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)


In [ ]:
model = Sequential()
model.add(Conv1D(256, 3, padding='same', strides=1, activation='relu'))
model.add(MaxPool1D(pool_size=2))
model.add(GRU(256))
model.add(Dense(cwe_count,activation="softmax"))
model.compile(optimizer=tf.optimizers.Adam(1e-3),
                  loss=tf.losses.categorical_crossentropy, metrics=['accuracy'])
model.fit(train_data, epochs=10)
score = model.evaluate(np.array(x_test), y_test)
print('last score:', score)

Epoch 1/10
855/855 [==============================] - 51s 57ms/step - loss: 1.3160 - accuracy: 0.5979
Epoch 2/10
855/855 [==============================] - 49s 58ms/step - loss: 0.6137 - accuracy: 0.8126
Epoch 3/10
855/855 [==============================] - 52s 61ms/step - loss: 0.5235 - accuracy: 0.8373
Epoch 4/10
855/855 [==============================] - 50s 58ms/step - loss: 0.4414 - accuracy: 0.8636
Epoch 5/10
855/855 [==============================] - 52s 61ms/step - loss: 0.3580 - accuracy: 0.8908
Epoch 6/10
855/855 [==============================] - 49s 58ms/step - loss: 0.2880 - accuracy: 0.9134
Epoch 7/10
384/855 [============>.................] - ETA: 27s - loss: 0.2523 - accuracy: 0.9252

In [39]:
print(y_test.shape)
print(np.shape(x_test))
model.evaluate(x_test,y_test)

(6834, 18)
(6834, 30, 100)


In [52]:
# score = model.evaluate(x_test, y_test)
# print('last score:', score)
x_test = np.array(x_test)
print(x_test[:2].shape)
print(model.predict(x_test[:2]))
score = model.evaluate(x_test,y_test)
print(score)

(2, 30, 100)
[[4.4170562e-08 1.8492882e-07 1.4880713e-06 1.7856941e-08 4.5001389e-08
  1.8838587e-07 5.9186033e-05 6.9560074e-06 8.3876337e-08 1.6891009e-08
  4.5630381e-07 2.6459647e-08 8.6402792e-08 9.9987423e-01 3.8792794e-05
  1.3154709e-06 2.6136324e-06 1.4269384e-05]
 [9.6406261e-08 7.2534234e-10 4.9477876e-08 3.3674036e-07 1.5675055e-06
  1.6289020e-08 4.8774386e-06 2.0043501e-06 2.6883624e-08 2.1965800e-09
  3.2655305e-07 1.2462021e-05 1.8913033e-09 3.9191826e-05 1.2439579e-05
  6.0230474e-09 9.9992263e-01 3.9611377e-06]]
214/214 [==============================] - 2s 9ms/step - loss: 0.8509 - accuracy: 0.8161
[0.8508539199829102, 0.8160667419433594]
