In [1]:
"""
Learn Layers in tensorflow
"""
import tensorflow as tf
from tensorflow.keras.layers import MaxPool1D, Conv1D, GRU
import numpy as np
x = tf.constant([1.,2.,3.,4.,5.])
x = tf.reshape(x,[1,5,1])
print(x)
max_pool_1d = MaxPool1D(pool_size=2,strides=1,padding='valid')
max_pool_1d(x)

tf.Tensor(
[[[1.]
  [2.]
  [3.]
  [4.]
  [5.]]], shape=(1, 5, 1), dtype=float32)


<tf.Tensor: shape=(1, 4, 1), dtype=float32, numpy=
array([[[2.],
        [3.],
        [4.],
        [5.]]], dtype=float32)>

In [2]:
input_shape = [1,3,1]
x = tf.random.normal(input_shape)
x = [[[1.],[1.],[1.]]]
x=  tf.constant(x)
print(np.shape(x))
y = Conv1D(2,2,activation='relu',input_shape=input_shape[1:])(x)
y

(1, 3, 1)


<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]]], dtype=float32)>

In [3]:
input_shape= [20,30,100]
wm = tf.random.normal(input_shape)
layer1 = Conv1D(2,3,activation='relu',input_shape= input_shape[1:])(wm)
layer1

<tf.Tensor: shape=(20, 28, 2), dtype=float32, numpy=
array([[[0.        , 1.6039804 ],
        [0.9145686 , 2.580305  ],
        [0.        , 0.5160057 ],
        ...,
        [0.        , 2.7873132 ],
        [3.693114  , 0.        ],
        [0.        , 0.        ]],

       [[1.7067192 , 0.9150018 ],
        [0.        , 0.        ],
        [0.        , 0.7701243 ],
        ...,
        [0.        , 0.65519875],
        [0.        , 0.        ],
        [0.42112482, 0.        ]],

       [[1.4880044 , 0.3027356 ],
        [0.        , 0.        ],
        [0.        , 0.        ],
        ...,
        [0.        , 0.        ],
        [0.13598765, 0.15189408],
        [0.7897397 , 0.        ]],

       ...,

       [[0.        , 1.2469391 ],
        [0.46807072, 1.6406808 ],
        [0.        , 0.        ],
        ...,
        [2.5997212 , 0.732676  ],
        [0.52731144, 1.542029  ],
        [0.42691672, 0.        ]],

       [[0.6965454 , 1.161411  ],
        [1.024043  , 0. 

In [4]:
layer2 = MaxPool1D(pool_size=2,
   strides=2, padding='valid')(layer1)
layer2

<tf.Tensor: shape=(20, 14, 2), dtype=float32, numpy=
array([[[9.1456860e-01, 2.5803051e+00],
        [2.0474885e-01, 6.3243514e-01],
        [2.0467064e+00, 5.3047132e-01],
        [1.4482818e+00, 3.2706716e+00],
        [7.3746592e-02, 1.5758671e+00],
        [1.0426745e+00, 1.2824866e+00],
        [7.3544759e-01, 8.9568615e-01],
        [0.0000000e+00, 3.9637065e-01],
        [1.5404316e+00, 1.2741896e+00],
        [3.7696984e-01, 0.0000000e+00],
        [3.4753764e+00, 7.2784793e-01],
        [5.0318021e-01, 1.7835721e-01],
        [5.7890815e-01, 2.7873132e+00],
        [3.6931140e+00, 0.0000000e+00]],

       [[1.7067192e+00, 9.1500181e-01],
        [3.3415796e-04, 8.1329608e-01],
        [0.0000000e+00, 1.4067395e+00],
        [8.5617638e-01, 1.3880607e+00],
        [2.2018781e+00, 1.0162956e+00],
        [1.4834468e+00, 4.4006798e-01],
        [5.5318320e-01, 2.1074607e+00],
        [1.2033951e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00],
        [1.2225063e+00, 1

In [5]:
layer3 = GRU(5,return_sequences=True)(layer2)
layer3
layer4 = GRU(5)(layer3)
layer4

<tf.Tensor: shape=(20, 5), dtype=float32, numpy=
array([[-0.48968518, -0.07383949,  0.39196992, -0.00261487, -0.4233189 ],
       [-0.35653067, -0.13816361,  0.24048269,  0.08555895, -0.31176516],
       [-0.36138293,  0.00381508,  0.31222364,  0.22117852, -0.4287161 ],
       [-0.40787303, -0.03971384,  0.3299732 ,  0.2673663 , -0.45297518],
       [-0.27773643,  0.15283975,  0.2544281 ,  0.40558824, -0.4914708 ],
       [-0.37256882,  0.03848651,  0.33050665,  0.21168248, -0.473759  ],
       [-0.36261195,  0.01373107,  0.30994853,  0.24882881, -0.4829231 ],
       [-0.50270706, -0.15719289,  0.36227804,  0.04895919, -0.48052543],
       [-0.34731513, -0.02975465,  0.2826956 ,  0.22463949, -0.38810995],
       [-0.3794499 , -0.16693184,  0.2531196 , -0.03686989, -0.29964283],
       [-0.42911738,  0.04550409,  0.37682018,  0.2402304 , -0.5042919 ],
       [-0.41639036, -0.08761028,  0.32095253,  0.14556165, -0.40386668],
       [-0.43550837, -0.15540227,  0.32041436,  0.13736297, -0.

In [6]:
output =tf.keras.layers.Dense(5)(layer4)
output

<tf.Tensor: shape=(20, 5), dtype=float32, numpy=
array([[-0.7669408 ,  0.11963415, -0.25035134, -0.08728943,  0.554109  ],
       [-0.60469705,  0.04267472, -0.10563806, -0.08405496,  0.38833532],
       [-0.7457453 ,  0.14078277, -0.11239612, -0.05222624,  0.42032495],
       [-0.8336673 ,  0.14405003, -0.1095674 , -0.06926303,  0.46446353],
       [-0.74448776,  0.18288869, -0.0287002 , -0.00963173,  0.32401037],
       [-0.77130413,  0.14716685, -0.123409  , -0.04634888,  0.43754274],
       [-0.7856035 ,  0.12669465, -0.08481547, -0.05103179,  0.4238194 ],
       [-0.84023017,  0.05165601, -0.17173943, -0.10959327,  0.5614333 ],
       [-0.7094057 ,  0.12352839, -0.095247  , -0.05805455,  0.3962325 ],
       [-0.5622405 ,  0.01150411, -0.14732715, -0.09332287,  0.41412607],
       [-0.8602516 ,  0.18671873, -0.16191617, -0.05299669,  0.49750692],
       [-0.7556892 ,  0.10472837, -0.14206934, -0.08079796,  0.4686243 ],
       [-0.8001986 ,  0.05898562, -0.11207187, -0.09888879,  0.

In [12]:
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.layers import Input
wm = tf.random.normal([5,3,10])
wm  =tf.expand_dims(wm,3)
input_token = Input(shape=[3,10])
resnet_layer = ResNet50(include_top=False,weights=None)
# print(resnet_layer.summary())
y = resnet_layer(wm)

ValueError: Input 0 of layer conv1_conv is incompatible with the layer: expected axis -1 of input shape to have value 3 but received input with shape (5, 9, 16, 1)

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from gensim.models import word2vec  # 导入gensim包
from tensorflow.python.keras.models import Sequential
import re
from nltk.stem import WordNetLemmatizer

def clean_text(text):
    text = re.sub('[^a-zA-Z]', ' ', text)
    words = text.lower().split()
    lemmatizer = WordNetLemmatizer()
    lem_words = [lemmatizer.lemmatize(w, pos='n') for w in words]
    stopwords = {}.fromkeys([line.rstrip() for line in open('F:\\PycharmProjects\\NVDproject\\nvdcve\\stopwords.txt')])
    eng_stopwords = set(stopwords)
    words = [w for w in lem_words if w not in eng_stopwords]
    return words

years = ['2020','2021','2022']
infix = ''
infix = str(years[0])
for i in range(1,len(years)):
    infix += '-'+str(years[i])

# cwe_min_count = 500
cwe_min_count = 700
infix+='_'+str(cwe_min_count)

vec_len = 100
# vec_len = 200
# vec_len = 300
min_count = 1
window_len = 5
dense_unit = 128
wv_model_path  = '..//..//models//wv//'+infix+"_"+str(vec_len)+"_"+str(min_count)+"_"+str(window_len)+'.pkl'
label_path = '..\\..\\data\\clean\\nvdcve-1.1-'+infix+'_labels.csv'
n=30

cwe_count = 18  # 2020,2021,2022_700

def get_label_one_hot(list):
    values = np.array(list)
    n_values = np.max(values) + 1
    return np.eye(n_values)[values]

from tensorflow.keras.layers import Conv1D,Conv2D, BatchNormalization, Activation, MaxPool1D,MaxPool2D, Dropout, Flatten, Dense, GRU
from tensorflow.keras import Model

class TextCNN(Model):
    def __init__(self):
        super(TextCNN, self).__init__()
        self.c1 = Conv2D(filters=12, kernel_size=(3, vec_len), padding='same')  # 卷积层
        self.b1 = BatchNormalization()  # BN层
        self.a1 = Activation('relu')  # 激活层
        self.p1 = MaxPool2D(pool_size=(2, 2), strides=2, padding='same')  # 池化层
        self.d1 = Dropout(0.2)  # dropout层

        self.flatten = Flatten()
        self.f1 = Dense(dense_unit, activation='relu')
        self.d2 = Dropout(0.2)
        self.f2 = Dense(cwe_count, activation='softmax')

    def call(self, x):
        x = self.c1(x)
        x = self.b1(x)
        x = self.a1(x)
        x = self.p1(x)
        x = self.d1(x)

        x = self.flatten(x)
        x = self.f1(x)
        x = self.d2(x)
        y = self.f2(x)
        return y




if __name__ == '__main__':
    wv_model = word2vec.Word2Vec.load(wv_model_path)
    dataset = pd.read_csv(label_path, header=None)
    dataset.columns = ['cve_id', 'cwe_id', 'descript', 'label']
    dataset['contents'] = dataset['descript'].apply(clean_text)
    train_dataset = []
    for line in dataset['contents']:
        length = len(line)
        if length > n:
            line = line[:n]
            word2vec_matrix = (wv_model.wv[line])
            train_dataset.append(word2vec_matrix)
        else:
            word2vec_matrix = (wv_model.wv[line])
            pad_length = n - length
            pad_matrix = np.zeros([pad_length, vec_len]) + 1e-10
            word2vec_matrix = np.concatenate([word2vec_matrix, pad_matrix], axis=0)
            train_dataset.append(word2vec_matrix)
    # train_dataset = np.expand_dims(train_dataset, 3)
    label_dataset = get_label_one_hot(dataset['label'])

In [2]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(train_dataset, label_dataset, test_size=0.2, random_state=217)
batch_size = 32
train_data = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(batch_size)

In [3]:
train_data

<BatchDataset shapes: ((None, 30, 100), (None, 18)), types: (tf.float64, tf.float64)>

In [15]:
# for i in x_test:
#     print(i.shape)
for i in x_train:
    print(i.shape)
print("x_train_len",len(train_data))
# for i in y_test:
#     print(i.shape)

(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)


In [ ]:
model = Sequential()
model.add(Conv1D(256, 3, padding='same', strides=1, activation='relu'))
model.add(MaxPool1D(pool_size=2))
model.add(GRU(256))
model.add(Dense(cwe_count,activation="softmax"))
model.compile(optimizer=tf.optimizers.Adam(1e-3),
                  loss=tf.losses.categorical_crossentropy, metrics=['accuracy'])
model.fit(train_data, epochs=10)
score = model.evaluate(np.array(x_test), y_test)
print('last score:', score)

Epoch 1/10
855/855 [==============================] - 51s 57ms/step - loss: 1.3160 - accuracy: 0.5979
Epoch 2/10
855/855 [==============================] - 49s 58ms/step - loss: 0.6137 - accuracy: 0.8126
Epoch 3/10
855/855 [==============================] - 52s 61ms/step - loss: 0.5235 - accuracy: 0.8373
Epoch 4/10
855/855 [==============================] - 50s 58ms/step - loss: 0.4414 - accuracy: 0.8636
Epoch 5/10
855/855 [==============================] - 52s 61ms/step - loss: 0.3580 - accuracy: 0.8908
Epoch 6/10
855/855 [==============================] - 49s 58ms/step - loss: 0.2880 - accuracy: 0.9134
Epoch 7/10
384/855 [============>.................] - ETA: 27s - loss: 0.2523 - accuracy: 0.9252

In [39]:
print(y_test.shape)
print(np.shape(x_test))
model.evaluate(x_test,y_test)

(6834, 18)
(6834, 30, 100)


In [52]:
# score = model.evaluate(x_test, y_test)
# print('last score:', score)
x_test = np.array(x_test)
print(x_test[:2].shape)
print(model.predict(x_test[:2]))
score = model.evaluate(x_test,y_test)
print(score)

(2, 30, 100)
[[4.4170562e-08 1.8492882e-07 1.4880713e-06 1.7856941e-08 4.5001389e-08
  1.8838587e-07 5.9186033e-05 6.9560074e-06 8.3876337e-08 1.6891009e-08
  4.5630381e-07 2.6459647e-08 8.6402792e-08 9.9987423e-01 3.8792794e-05
  1.3154709e-06 2.6136324e-06 1.4269384e-05]
 [9.6406261e-08 7.2534234e-10 4.9477876e-08 3.3674036e-07 1.5675055e-06
  1.6289020e-08 4.8774386e-06 2.0043501e-06 2.6883624e-08 2.1965800e-09
  3.2655305e-07 1.2462021e-05 1.8913033e-09 3.9191826e-05 1.2439579e-05
  6.0230474e-09 9.9992263e-01 3.9611377e-06]]
214/214 [==============================] - 2s 9ms/step - loss: 0.8509 - accuracy: 0.8161
[0.8508539199829102, 0.8160667419433594]
