In [1]:
"""
Learn Layers in tensorflow
"""
import tensorflow as tf
from tensorflow.keras.layers import MaxPool1D, Conv1D, GRU, Embedding
import numpy as np
x = tf.constant([1.,2.,3.,4.,5.])
x = tf.reshape(x,[1,5,1])
print(x)
max_pool_1d = MaxPool1D(pool_size=2,strides=1,padding='valid')
max_pool_1d(x)

tf.Tensor(
[[[1.]
  [2.]
  [3.]
  [4.]
  [5.]]], shape=(1, 5, 1), dtype=float32)


<tf.Tensor: shape=(1, 4, 1), dtype=float32, numpy=
array([[[2.],
        [3.],
        [4.],
        [5.]]], dtype=float32)>

In [2]:
input_shape = [1,3,1]
x = tf.random.normal(input_shape)
x = [[[1.],[1.],[1.]]]
x=  tf.constant(x)
print(np.shape(x))
y = Conv1D(2,2,activation='relu',input_shape=input_shape[1:])(x)
y

(1, 3, 1)


<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[0.3705442 , 0.37535143],
        [0.3705442 , 0.37535143]]], dtype=float32)>

In [3]:
input_shape= [20,30,100]
wm = tf.random.normal(input_shape)
layer1 = Conv1D(2,3,activation='relu',input_shape= input_shape[1:])(wm)
layer1

<tf.Tensor: shape=(20, 28, 2), dtype=float32, numpy=
array([[[0.        , 0.        ],
        [0.12981394, 2.5327737 ],
        [0.        , 0.        ],
        ...,
        [0.        , 0.        ],
        [2.543246  , 0.        ],
        [2.1164474 , 0.        ]],

       [[1.1042296 , 1.1165943 ],
        [0.9595297 , 0.        ],
        [0.0957472 , 0.        ],
        ...,
        [1.0798073 , 1.6285172 ],
        [0.        , 0.        ],
        [0.56875354, 1.0047684 ]],

       [[0.852252  , 0.        ],
        [1.3395736 , 0.        ],
        [2.6895547 , 0.4092197 ],
        ...,
        [0.        , 1.4104731 ],
        [0.07447787, 0.74301666],
        [0.        , 0.        ]],

       ...,

       [[0.03631218, 0.        ],
        [0.10401431, 0.        ],
        [0.        , 1.5930809 ],
        ...,
        [2.026839  , 1.3257364 ],
        [0.        , 0.        ],
        [0.        , 1.0856842 ]],

       [[1.4297205 , 1.384232  ],
        [0.        , 0. 

In [4]:
layer2 = MaxPool1D(pool_size=2,
   strides=2, padding='valid')(layer1)
layer2

<tf.Tensor: shape=(20, 14, 2), dtype=float32, numpy=
array([[[1.29813939e-01, 2.53277373e+00],
        [9.77449000e-01, 0.00000000e+00],
        [5.78199923e-01, 0.00000000e+00],
        [1.16281438e+00, 0.00000000e+00],
        [2.29153681e+00, 2.22632599e+00],
        [3.28911662e+00, 1.66283235e-01],
        [1.34279716e+00, 0.00000000e+00],
        [1.67944217e+00, 1.39474481e-01],
        [0.00000000e+00, 1.08330929e+00],
        [2.15718913e+00, 1.64969516e+00],
        [2.61781782e-01, 2.47143793e+00],
        [5.12810528e-01, 4.15932029e-01],
        [1.61927760e+00, 0.00000000e+00],
        [2.54324603e+00, 0.00000000e+00]],

       [[1.10422957e+00, 1.11659431e+00],
        [2.28727594e-01, 0.00000000e+00],
        [3.00600386e+00, 0.00000000e+00],
        [4.22689497e-01, 0.00000000e+00],
        [1.58070076e+00, 3.04988116e-01],
        [2.10211921e+00, 0.00000000e+00],
        [0.00000000e+00, 2.37793255e+00],
        [1.52901411e+00, 1.21134889e+00],
        [1.47008121e+

In [5]:
layer3 = GRU(5,return_sequences=True)(layer2)
layer3
layer4 = GRU(5)(layer3)
layer4

<tf.Tensor: shape=(20, 5), dtype=float32, numpy=
array([[-0.4772205 ,  0.34644255,  0.18360162,  0.42968497,  0.25573996],
       [-0.4827305 ,  0.43263137, -0.0251802 ,  0.09253262,  0.12441064],
       [-0.43710572,  0.3331321 ,  0.00886732,  0.21585827,  0.13021545],
       [-0.43283165,  0.3316018 ,  0.09965979,  0.28184026,  0.20034365],
       [-0.60682046,  0.4092531 ,  0.00856436,  0.19283606,  0.23395665],
       [-0.41720885,  0.31538025,  0.11153869,  0.38031745,  0.20224938],
       [-0.44531193,  0.36453882,  0.02961163,  0.3173172 ,  0.1816997 ],
       [-0.39128134,  0.37680253, -0.00972832,  0.1994336 ,  0.11111055],
       [-0.55177   ,  0.4732882 , -0.137559  ,  0.20953427,  0.12957709],
       [-0.4646443 ,  0.38897997,  0.06751792,  0.2779581 ,  0.19466685],
       [-0.22283547,  0.18347405,  0.07225328,  0.27090773,  0.11487617],
       [-0.46439463,  0.42313087, -0.12079337, -0.01209377,  0.08029446],
       [-0.26842105,  0.283847  , -0.00478735,  0.09674352,  0.

In [6]:
output =tf.keras.layers.Dense(5)(layer4)
output

<tf.Tensor: shape=(20, 5), dtype=float32, numpy=
array([[ 0.24917054, -0.7201454 ,  0.47529954, -0.01663303,  0.2578903 ],
       [-0.04054196, -0.4831873 ,  0.3504595 ,  0.32261035,  0.15989986],
       [ 0.06396246, -0.49805644,  0.34236848,  0.15802418,  0.20585757],
       [ 0.13259278, -0.568036  ,  0.3877536 ,  0.08115825,  0.1951032 ],
       [ 0.00912421, -0.56777847,  0.42685568,  0.23332635,  0.20286343],
       [ 0.20717673, -0.6270313 ,  0.40966052, -0.00378939,  0.23465696],
       [ 0.13389029, -0.5980087 ,  0.39938247,  0.08409256,  0.21768913],
       [ 0.0552035 , -0.5031051 ,  0.33639163,  0.18583354,  0.17779961],
       [-0.00830384, -0.5731907 ,  0.4006417 ,  0.2791747 ,  0.22713622],
       [ 0.11424319, -0.6049229 ,  0.41185755,  0.13100016,  0.20284912],
       [ 0.16077492, -0.39855915,  0.2491328 , -0.04280603,  0.1515107 ],
       [-0.13638593, -0.36700022,  0.28480464,  0.3965592 ,  0.12096143],
       [ 0.0078936 , -0.33331314,  0.23245333,  0.1581376 ,  0.

In [7]:
x  = tf.random.normal([1,3])
x = tf.constant([[1,2,3],[4,5,6]])
y = Embedding(10,3,input_length=2)(x)
y

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[-0.00668246, -0.04104529,  0.00752068],
        [-0.03777779,  0.03143077,  0.00583569],
        [-0.01990938, -0.03251102,  0.0392742 ]],

       [[-0.00709502, -0.03635586, -0.03421741],
        [ 0.01521512, -0.0347425 ,  0.00158464],
        [ 0.01520227,  0.02075157,  0.01165517]]], dtype=float32)>

In [12]:
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.layers import Input
wm = tf.random.normal([5,3,10])
wm  =tf.expand_dims(wm,3)
input_token = Input(shape=[3,10])
resnet_layer = ResNet50(include_top=False,weights=None)
# print(resnet_layer.summary())
y = resnet_layer(wm)

ValueError: Input 0 of layer conv1_conv is incompatible with the layer: expected axis -1 of input shape to have value 3 but received input with shape (5, 9, 16, 1)

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from gensim.models import word2vec  # 导入gensim包
from tensorflow.python.keras.models import Sequential
import re
from nltk.stem import WordNetLemmatizer

def clean_text(text):
    text = re.sub('[^a-zA-Z]', ' ', text)
    words = text.lower().split()
    lemmatizer = WordNetLemmatizer()
    lem_words = [lemmatizer.lemmatize(w, pos='n') for w in words]
    stopwords = {}.fromkeys([line.rstrip() for line in open('F:\\PycharmProjects\\NVDproject\\nvdcve\\stopwords.txt')])
    eng_stopwords = set(stopwords)
    words = [w for w in lem_words if w not in eng_stopwords]
    return words

years = ['2020','2021','2022']
infix = ''
infix = str(years[0])
for i in range(1,len(years)):
    infix += '-'+str(years[i])

# cwe_min_count = 500
cwe_min_count = 700
infix+='_'+str(cwe_min_count)

vec_len = 100
# vec_len = 200
# vec_len = 300
min_count = 1
window_len = 5
dense_unit = 128
wv_model_path  = '..//..//models//wv//'+infix+"_"+str(vec_len)+"_"+str(min_count)+"_"+str(window_len)+'.pkl'
label_path = '..\\..\\data\\clean\\nvdcve-1.1-'+infix+'_labels.csv'
n=30

cwe_count = 18  # 2020,2021,2022_700

def get_label_one_hot(list):
    values = np.array(list)
    n_values = np.max(values) + 1
    return np.eye(n_values)[values]

from tensorflow.keras.layers import Conv1D,Conv2D, BatchNormalization, Activation, MaxPool1D,MaxPool2D, Dropout, Flatten, Dense, GRU
from tensorflow.keras import Model

class TextCNN(Model):
    def __init__(self):
        super(TextCNN, self).__init__()
        self.c1 = Conv2D(filters=12, kernel_size=(3, vec_len), padding='same')  # 卷积层
        self.b1 = BatchNormalization()  # BN层
        self.a1 = Activation('relu')  # 激活层
        self.p1 = MaxPool2D(pool_size=(2, 2), strides=2, padding='same')  # 池化层
        self.d1 = Dropout(0.2)  # dropout层

        self.flatten = Flatten()
        self.f1 = Dense(dense_unit, activation='relu')
        self.d2 = Dropout(0.2)
        self.f2 = Dense(cwe_count, activation='softmax')

    def call(self, x):
        x = self.c1(x)
        x = self.b1(x)
        x = self.a1(x)
        x = self.p1(x)
        x = self.d1(x)

        x = self.flatten(x)
        x = self.f1(x)
        x = self.d2(x)
        y = self.f2(x)
        return y




if __name__ == '__main__':
    wv_model = word2vec.Word2Vec.load(wv_model_path)
    dataset = pd.read_csv(label_path, header=None)
    dataset.columns = ['cve_id', 'cwe_id', 'descript', 'label']
    dataset['contents'] = dataset['descript'].apply(clean_text)
    train_dataset = []
    for line in dataset['contents']:
        length = len(line)
        if length > n:
            line = line[:n]
            word2vec_matrix = (wv_model.wv[line])
            train_dataset.append(word2vec_matrix)
        else:
            word2vec_matrix = (wv_model.wv[line])
            pad_length = n - length
            pad_matrix = np.zeros([pad_length, vec_len]) + 1e-10
            word2vec_matrix = np.concatenate([word2vec_matrix, pad_matrix], axis=0)
            train_dataset.append(word2vec_matrix)
    # train_dataset = np.expand_dims(train_dataset, 3)
    label_dataset = get_label_one_hot(dataset['label'])

In [2]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(train_dataset, label_dataset, test_size=0.2, random_state=217)
batch_size = 32
train_data = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(batch_size)

In [3]:
train_data

<BatchDataset shapes: ((None, 30, 100), (None, 18)), types: (tf.float64, tf.float64)>

In [15]:
# for i in x_test:
#     print(i.shape)
for i in x_train:
    print(i.shape)
print("x_train_len",len(train_data))
# for i in y_test:
#     print(i.shape)

(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)
(30, 100)


In [ ]:
model = Sequential()
model.add(Conv1D(256, 3, padding='same', strides=1, activation='relu'))
model.add(MaxPool1D(pool_size=2))
model.add(GRU(256))
model.add(Dense(cwe_count,activation="softmax"))
model.compile(optimizer=tf.optimizers.Adam(1e-3),
                  loss=tf.losses.categorical_crossentropy, metrics=['accuracy'])
model.fit(train_data, epochs=10)
score = model.evaluate(np.array(x_test), y_test)
print('last score:', score)

Epoch 1/10
855/855 [==============================] - 51s 57ms/step - loss: 1.3160 - accuracy: 0.5979
Epoch 2/10
855/855 [==============================] - 49s 58ms/step - loss: 0.6137 - accuracy: 0.8126
Epoch 3/10
855/855 [==============================] - 52s 61ms/step - loss: 0.5235 - accuracy: 0.8373
Epoch 4/10
855/855 [==============================] - 50s 58ms/step - loss: 0.4414 - accuracy: 0.8636
Epoch 5/10
855/855 [==============================] - 52s 61ms/step - loss: 0.3580 - accuracy: 0.8908
Epoch 6/10
855/855 [==============================] - 49s 58ms/step - loss: 0.2880 - accuracy: 0.9134
Epoch 7/10
384/855 [============>.................] - ETA: 27s - loss: 0.2523 - accuracy: 0.9252

In [39]:
print(y_test.shape)
print(np.shape(x_test))
model.evaluate(x_test,y_test)

(6834, 18)
(6834, 30, 100)


In [52]:
# score = model.evaluate(x_test, y_test)
# print('last score:', score)
x_test = np.array(x_test)
print(x_test[:2].shape)
print(model.predict(x_test[:2]))
score = model.evaluate(x_test,y_test)
print(score)

(2, 30, 100)
[[4.4170562e-08 1.8492882e-07 1.4880713e-06 1.7856941e-08 4.5001389e-08
  1.8838587e-07 5.9186033e-05 6.9560074e-06 8.3876337e-08 1.6891009e-08
  4.5630381e-07 2.6459647e-08 8.6402792e-08 9.9987423e-01 3.8792794e-05
  1.3154709e-06 2.6136324e-06 1.4269384e-05]
 [9.6406261e-08 7.2534234e-10 4.9477876e-08 3.3674036e-07 1.5675055e-06
  1.6289020e-08 4.8774386e-06 2.0043501e-06 2.6883624e-08 2.1965800e-09
  3.2655305e-07 1.2462021e-05 1.8913033e-09 3.9191826e-05 1.2439579e-05
  6.0230474e-09 9.9992263e-01 3.9611377e-06]]
214/214 [==============================] - 2s 9ms/step - loss: 0.8509 - accuracy: 0.8161
[0.8508539199829102, 0.8160667419433594]
